modLoader = "javafml"
loaderVersion = "[56,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "combatlog"
version = "${version}"
displayName = "CombatLog"
# We don't need to create custom test, IGNORE_SERVER_VERSION according to forge docs is perfect for server side mod
displayTest="IGNORE_SERVER_VERSION"
authors = "WildToastyMop"
description = '''
An attempt to prevent people from logging out while in combat with another player
'''
logoFile = "icon.png"

[[dependencies.combatlog]]
modId = "forge"
mandatory = true
versionRange = "[56,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.combatlog]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.6,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config="combatlog.mixins.json"
