modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "combatlog"
version = "${version}"
displayName = "CombatLog"
displayTest="IGNORE_SERVER_VERSION"
authors = "WildToastyMop"
description = '''
An attempt to prevent people from logging out while in combat with another player
'''
logoFile = "assets/combatlog/icon.png"

[[dependencies.combatlog]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.combatlog]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2]"
ordering = "NONE"
side = "SERVER"
