modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "combatlog"
version = "${version}"
displayName = "CombatLog"
authors = "WildToastyMop"
description = '''
An attempt to prevent people from logging out while in combat with another player
'''
#logoFile = ""

[[dependencies.combatlog]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.combatlog]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "combatlog-common.mixins.json"
