modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "combatlog"
version = "${version}"
displayName = "CombatLog"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[dependencies.combatlog]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.combatlog]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "combatlog.mixins.json"
