modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "combatlog"
version = "${version}"
displayName = "CombatLog"
authors = "WildToastyMop"
description = '''
An attempt to prevent people from logging out while in combat with another player
'''
logoFile = "icon.png"

[[dependencies.combatlog]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.combatlog]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "combatlog.mixins.json"
